### PR TITLE
Export fn encode::encode(..)

### PR DESCRIPTION
**Pull request by alexbiehl**
My use case requires me to suspend and restart encoding of Avro containers. Exposing the low-level encode function allows for encoding Avro values without relying on the `Writer`, which offers no way to "resume" writing but always writes out the schema. 

It's a somewhat manual process but until we know better abstractions for the problem we can add those.

### CODE REVIEW

**Comment by Igosuki** [comment]
You're not alone, I've also forked it for that purpose originally.

**Comment by poros** [comment]
I am a bit worried of adding to the public API more internal functions, although the signature seems to be pretty stable.

We have already added to the public API `to_avro_datum` (see https://docs.rs/avro-rs/0.10.0/avro_rs/fn.to_avro_datum.html), which is very close to `encode` but with added validation and the creation of a buffer. Would that be sufficient for your use case? I am asking because this function is easy to miss, as it isn't mentioned in the README.

**Comment by poros** [comment]
Ah, if we ever decide to make `encode` public, I believe that we would probably want to make `decode` public, too, for simmetry.

**Comment by alexbiehl** [comment]
Ah! I did not see to_avro_datum before. I think it'll work for me. Thanks @poros!

**Comment by poros** [comment]
Ah, happy that your use case has already been covered. Shall we close this PR?

**Pull request closed without merging**
