### PR TITLE
allow Value::Bytes to be assigned to Schema::Fixed ...

### PR DESCRIPTION
**Pull request by dgrijalva-squire**
... as long as the length matches. This seems needed to enable Serde and serde-bytes to provide Fixed values.

### CODE REVIEW

**Comment by dgrijalva-squire** [comment]
Not sure why the tests failed. The all pass when I run locally. It looks like it was an issue with the test system rather than the code.

**Comment by poros** [comment]
Hello, sorry for the late reply!

Could you try to rebase on master and to run `cargo fmt`? We had clippy failing in master, but now it should be fixed,  while `cargo fmt` seems to fail for your branch.

**Comment by poros** [comment]
Hello! As of today, I am stepping down as a maintainer of this library for a while (see #174). Please ping @flavray from now on.
Thanks again for your contribution :)

**Comment by dgrijalva-squire** [comment]
@flavray merge and formatted, as requested. 

tests pass locally. we'll see if they are able to run now. there was some permissions error last time.

**Review by flavray — APPROVED** [review]
Looks good to me, thank you for the contribution!

**Comment by flavray** [comment]
`v0.13.0` has just been released with this change. 🙂

**Pull request merged**
