### PR TITLE
Negative block lengths are not handled

### PR DESCRIPTION
**Pull request by mkroli**
see flavray/avro-rs#69

### CODE REVIEW

**Comment by poros** [comment]
Thanks for contributing! The code looks good to me. Would you be so kind to also add a test to be sure this works as intended and to avoid regression?

**Comment by poros** [comment]
Thanks for adding the tests! The change looks good but Travis is failing because of some formatting error. Could you please run `cargo fmt` or, even better, run the pre-commit hooks on your branch? I'll merge it and release a new patch version as soon as Travis is green

**Comment by mkroli** [comment]
Thanks for the great project. I committed the changes as requested

**Comment by poros** [comment]
Thanks for contributing!

**Pull request merged**
