### PR TITLE
WIP: Logical types

### PR DESCRIPTION
**Pull request by Snnappie**
I did this work a while back for an internal project which requires using Avro [Logical Types](https://avro.apache.org/docs/current/spec.html#Logical+Types).

If you are interested in this, I can fix up the merge conflicts and complete the implementation.

### CODE REVIEW

**Comment by alecmocatta** [comment]
I for one would be interested in this!

**Comment by Snnappie** [comment]
@alecmocatta I might have some time tomorrow or this weekend to finish this.

@flavray Thoughts?

**Comment by flavray** [comment]
I only skimmed through the changes, they look promising!
Definitely interested in having support of logical types in the next version, go for it. Happy to review changes whenever you feel like it’s good to go 🙂

**Comment by poros** [comment]
This is exciting and terrifying at the same time. I am still unsure whether logical types are better than just use native types...

**Comment by cpcloud** [comment]
@Snnappie @flavray I'm very interested in this. What else is need beyond resolving the merge conflicts to get this in?

**Comment by Snnappie** [comment]
@cpcloud I forgot about this. Let me regain the context and I'll give an update.

**Comment by cpcloud** [comment]
Cool, I've done the work to resolve the additional types and also fix some parsing issues related to logical types. Should I submit a PR to your fork?

**Comment by Snnappie** [comment]
@cpcloud Oh, great. Would you rather just open a new one to replace this PR instead?

**Comment by cpcloud** [comment]
Sure thing!

**Comment by poros** [comment]
Closed in favor of #111

**Pull request closed without merging**
